import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";
import NextTopLoader from "nextjs-toploader";
import { PiPProvider } from "@/context/pip-provider";
import Head from "next/head";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "Emodu - Emotion Detection for Remote Learning",
  description: "Emodu is an emotion detection tool that helps teachers understand their students' emotions during remote learning. Emodu uses AI to analyze students' facial expressions and provide real-time feedback to teachers.",
  keywords: "emotion detection, remote learning, AI, facial recognition, education, edtech, online meetings, virtual classrooms",
  authors: [{ name: "HCE RPL UPI Team" }],
  icons: [
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '192x192',
      url: '/icons/icon-192.png',
    },
  ]
};

<Head>
  <link rel="icon" href="/icons/favicon.ico" sizes="any" />
</Head>
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PiPProvider>

        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <NextTopLoader
            showSpinner={false}
            color="gray"
            crawlSpeed={100}
          />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >

            {children}
          </ThemeProvider>
          <Toaster richColors />
        </body>
      </PiPProvider>
    </html>
  );
}
